### ISSUE TITLE
about the listener in the document.body

### ISSUE THREAD

**Issue by felixzapata** [PolymerElements/iron-page-url#17]
Hi, this is more a question that an issue, I think. Why is there a listener to all clicks in the `document.body`?

```
this.unlisten(/** @type {!HTMLBodyElement} */(document.body), 'click', '_globalOnClick');
```

I have an small router component that wraps a router library. This library fires some events and when I add the iron-page-url to show and debug some information in my demo, the router stops working due to the `event.preventDefault()`.

My demo has some links and one `iron-pages` component to show how the element changes when the user clicks in the links.

Regards.

**Comment by rictic** [comment]
It does this so that links within a single page app work as expected, causing the URL to be updated but preventing the page from being reloaded. You can disable this behavior by giving a URL space regex that matches no valid URLs. For example: `url-space-regex="^$"`

It seems like wanting this behavior disabled is somewhat common, we may add an additional property just to disable it.
